/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedContratantesRouteImport } from './routes/_authenticated/contratantes'
import { Route as AuthenticatedContratoRouteImport } from './routes/_authenticated/contrato'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFormacoesRouteImport } from './routes/_authenticated/formacoes'
import { Route as AuthenticatedGeradorCardsRouteImport } from './routes/_authenticated/gerador-cards'
import { Route as AuthenticatedMarcaRouteImport } from './routes/_authenticated/marca'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedRidersRouteImport } from './routes/_authenticated/riders'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as AuthenticatedEventosEventIdRouteImport } from './routes/_authenticated/eventos.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratantesRoute =
  AuthenticatedContratantesRouteImport.update({
    id: '/contratantes',
    path: '/contratantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratoRoute = AuthenticatedContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormacoesRoute = AuthenticatedFormacoesRouteImport.update({
  id: '/formacoes',
  path: '/formacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeradorCardsRoute =
  AuthenticatedGeradorCardsRouteImport.update({
    id: '/gerador-cards',
    path: '/gerador-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarcaRoute = AuthenticatedMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRidersRoute = AuthenticatedRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosEventIdRoute =
  AuthenticatedEventosEventIdRouteImport.update({
    id: '/eventos/$eventId',
    path: '/eventos/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contratantes': typeof AuthenticatedContratantesRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contratantes': typeof AuthenticatedContratantesRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contratantes': typeof AuthenticatedContratantesRoute
  '/_authenticated/contrato': typeof AuthenticatedContratoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/formacoes': typeof AuthenticatedFormacoesRoute
  '/_authenticated/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/_authenticated/marca': typeof AuthenticatedMarcaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/riders': typeof AuthenticatedRidersRoute
  '/_authenticated/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contratantes'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/formacoes'
    | '/gerador-cards'
    | '/marca'
    | '/perfil'
    | '/portfolio'
    | '/repertorio'
    | '/riders'
    | '/eventos/$eventId'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contratantes'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/formacoes'
    | '/gerador-cards'
    | '/marca'
    | '/perfil'
    | '/portfolio'
    | '/repertorio'
    | '/riders'
    | '/eventos/$eventId'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contratantes'
    | '/_authenticated/contrato'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/formacoes'
    | '/_authenticated/gerador-cards'
    | '/_authenticated/marca'
    | '/_authenticated/perfil'
    | '/_authenticated/portfolio'
    | '/_authenticated/repertorio'
    | '/_authenticated/riders'
    | '/_authenticated/eventos/$eventId'
    | '/_authenticated/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratantes': {
      id: '/_authenticated/contratantes'
      path: '/contratantes'
      fullPath: '/contratantes'
      preLoaderRoute: typeof AuthenticatedContratantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contrato': {
      id: '/_authenticated/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof AuthenticatedContratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formacoes': {
      id: '/_authenticated/formacoes'
      path: '/formacoes'
      fullPath: '/formacoes'
      preLoaderRoute: typeof AuthenticatedFormacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerador-cards': {
      id: '/_authenticated/gerador-cards'
      path: '/gerador-cards'
      fullPath: '/gerador-cards'
      preLoaderRoute: typeof AuthenticatedGeradorCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marca': {
      id: '/_authenticated/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof AuthenticatedMarcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riders': {
      id: '/_authenticated/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof AuthenticatedRidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$eventId': {
      id: '/_authenticated/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContratantesRoute: typeof AuthenticatedContratantesRoute
  AuthenticatedContratoRoute: typeof AuthenticatedContratoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFormacoesRoute: typeof AuthenticatedFormacoesRoute
  AuthenticatedGeradorCardsRoute: typeof AuthenticatedGeradorCardsRoute
  AuthenticatedMarcaRoute: typeof AuthenticatedMarcaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
  AuthenticatedRidersRoute: typeof AuthenticatedRidersRoute
  AuthenticatedEventosEventIdRoute: typeof AuthenticatedEventosEventIdRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContratantesRoute: AuthenticatedContratantesRoute,
  AuthenticatedContratoRoute: AuthenticatedContratoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFormacoesRoute: AuthenticatedFormacoesRoute,
  AuthenticatedGeradorCardsRoute: AuthenticatedGeradorCardsRoute,
  AuthenticatedMarcaRoute: AuthenticatedMarcaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
  AuthenticatedRidersRoute: AuthenticatedRidersRoute,
  AuthenticatedEventosEventIdRoute: AuthenticatedEventosEventIdRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
