/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModeloContratoShowRouteImport } from './routes/modelo-contrato-show'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedComecarRouteImport } from './routes/_authenticated/comecar'
import { Route as AuthenticatedContratantesRouteImport } from './routes/_authenticated/contratantes'
import { Route as AuthenticatedContratoRouteImport } from './routes/_authenticated/contrato'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFormacoesRouteImport } from './routes/_authenticated/formacoes'
import { Route as AuthenticatedGeradorCardsRouteImport } from './routes/_authenticated/gerador-cards'
import { Route as AuthenticatedMagicPasteRouteImport } from './routes/_authenticated/magic-paste'
import { Route as AuthenticatedMarcaRouteImport } from './routes/_authenticated/marca'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedRidersRouteImport } from './routes/_authenticated/riders'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as AuthenticatedEventosEventIdRouteImport } from './routes/_authenticated/eventos.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloContratoShowRoute = ModeloContratoShowRouteImport.update({
  id: '/modelo-contrato-show',
  path: '/modelo-contrato-show',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComecarRoute = AuthenticatedComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratantesRoute =
  AuthenticatedContratantesRouteImport.update({
    id: '/contratantes',
    path: '/contratantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratoRoute = AuthenticatedContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormacoesRoute = AuthenticatedFormacoesRouteImport.update({
  id: '/formacoes',
  path: '/formacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeradorCardsRoute =
  AuthenticatedGeradorCardsRouteImport.update({
    id: '/gerador-cards',
    path: '/gerador-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMagicPasteRoute = AuthenticatedMagicPasteRouteImport.update({
  id: '/magic-paste',
  path: '/magic-paste',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarcaRoute = AuthenticatedMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRidersRoute = AuthenticatedRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosEventIdRoute =
  AuthenticatedEventosEventIdRouteImport.update({
    id: '/eventos/$eventId',
    path: '/eventos/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/modelo-contrato-show': typeof ModeloContratoShowRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/comecar': typeof AuthenticatedComecarRoute
  '/contratantes': typeof AuthenticatedContratantesRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/magic-paste': typeof AuthenticatedMagicPasteRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/modelo-contrato-show': typeof ModeloContratoShowRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/comecar': typeof AuthenticatedComecarRoute
  '/contratantes': typeof AuthenticatedContratantesRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formacoes': typeof AuthenticatedFormacoesRoute
  '/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/magic-paste': typeof AuthenticatedMagicPasteRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/modelo-contrato-show': typeof ModeloContratoShowRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/comecar': typeof AuthenticatedComecarRoute
  '/_authenticated/contratantes': typeof AuthenticatedContratantesRoute
  '/_authenticated/contrato': typeof AuthenticatedContratoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/formacoes': typeof AuthenticatedFormacoesRoute
  '/_authenticated/gerador-cards': typeof AuthenticatedGeradorCardsRoute
  '/_authenticated/magic-paste': typeof AuthenticatedMagicPasteRoute
  '/_authenticated/marca': typeof AuthenticatedMarcaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/riders': typeof AuthenticatedRidersRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/eventos/$eventId': typeof AuthenticatedEventosEventIdRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/modelo-contrato-show'
    | '/nova-senha'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cobrancas'
    | '/comecar'
    | '/contratantes'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/formacoes'
    | '/gerador-cards'
    | '/magic-paste'
    | '/marca'
    | '/perfil'
    | '/portfolio'
    | '/repertorio'
    | '/riders'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/eventos/$eventId'
    | '/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/modelo-contrato-show'
    | '/nova-senha'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cobrancas'
    | '/comecar'
    | '/contratantes'
    | '/contrato'
    | '/dashboard'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/formacoes'
    | '/gerador-cards'
    | '/magic-paste'
    | '/marca'
    | '/perfil'
    | '/portfolio'
    | '/repertorio'
    | '/riders'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/eventos/$eventId'
    | '/eventos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/modelo-contrato-show'
    | '/nova-senha'
    | '/privacidade'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/cobrancas'
    | '/_authenticated/comecar'
    | '/_authenticated/contratantes'
    | '/_authenticated/contrato'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/formacoes'
    | '/_authenticated/gerador-cards'
    | '/_authenticated/magic-paste'
    | '/_authenticated/marca'
    | '/_authenticated/perfil'
    | '/_authenticated/portfolio'
    | '/_authenticated/repertorio'
    | '/_authenticated/riders'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/eventos/$eventId'
    | '/_authenticated/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ModeloContratoShowRoute: typeof ModeloContratoShowRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-contrato-show': {
      id: '/modelo-contrato-show'
      path: '/modelo-contrato-show'
      fullPath: '/modelo-contrato-show'
      preLoaderRoute: typeof ModeloContratoShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comecar': {
      id: '/_authenticated/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof AuthenticatedComecarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratantes': {
      id: '/_authenticated/contratantes'
      path: '/contratantes'
      fullPath: '/contratantes'
      preLoaderRoute: typeof AuthenticatedContratantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contrato': {
      id: '/_authenticated/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof AuthenticatedContratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formacoes': {
      id: '/_authenticated/formacoes'
      path: '/formacoes'
      fullPath: '/formacoes'
      preLoaderRoute: typeof AuthenticatedFormacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerador-cards': {
      id: '/_authenticated/gerador-cards'
      path: '/gerador-cards'
      fullPath: '/gerador-cards'
      preLoaderRoute: typeof AuthenticatedGeradorCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magic-paste': {
      id: '/_authenticated/magic-paste'
      path: '/magic-paste'
      fullPath: '/magic-paste'
      preLoaderRoute: typeof AuthenticatedMagicPasteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marca': {
      id: '/_authenticated/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof AuthenticatedMarcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riders': {
      id: '/_authenticated/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof AuthenticatedRidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$eventId': {
      id: '/_authenticated/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedComecarRoute: typeof AuthenticatedComecarRoute
  AuthenticatedContratantesRoute: typeof AuthenticatedContratantesRoute
  AuthenticatedContratoRoute: typeof AuthenticatedContratoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFormacoesRoute: typeof AuthenticatedFormacoesRoute
  AuthenticatedGeradorCardsRoute: typeof AuthenticatedGeradorCardsRoute
  AuthenticatedMagicPasteRoute: typeof AuthenticatedMagicPasteRoute
  AuthenticatedMarcaRoute: typeof AuthenticatedMarcaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
  AuthenticatedRidersRoute: typeof AuthenticatedRidersRoute
  AuthenticatedEventosEventIdRoute: typeof AuthenticatedEventosEventIdRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedComecarRoute: AuthenticatedComecarRoute,
  AuthenticatedContratantesRoute: AuthenticatedContratantesRoute,
  AuthenticatedContratoRoute: AuthenticatedContratoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFormacoesRoute: AuthenticatedFormacoesRoute,
  AuthenticatedGeradorCardsRoute: AuthenticatedGeradorCardsRoute,
  AuthenticatedMagicPasteRoute: AuthenticatedMagicPasteRoute,
  AuthenticatedMarcaRoute: AuthenticatedMarcaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
  AuthenticatedRidersRoute: AuthenticatedRidersRoute,
  AuthenticatedEventosEventIdRoute: AuthenticatedEventosEventIdRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ModeloContratoShowRoute: ModeloContratoShowRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
